title: Default File

columns:
  - width: 1/1
    sections:
      fields:
        type: fields
        fields:
          caption:
            label: Caption
            type: text
            icon: text
            counter: false
            width: 1/2
          alt:
            label: Alt Text
            type: text
            counter: false
            icon: search
            width: 1/2
